[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jdmtool"
version = "0.0.1"
dependencies = [
    'libusb1>=2.0.1',
    'platformdirs>=2.6.2',
    'requests>=2.26.0',
    'tqdm>=4.1.0',
]

[project.scripts]
jdmtool = "jdmtool.main:main"
